//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeClient.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        double GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convert", ReplyAction="http://tempuri.org/IService1/ConvertResponse")]
        double Convert(string fromCurrency, string toCurrency, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Convert", ReplyAction="http://tempuri.org/IService1/ConvertResponse")]
        System.Threading.Tasks.Task<double> ConvertAsync(string fromCurrency, string toCurrency, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        double BuyCurrency(string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<double> BuyCurrencyAsync(string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        double SellCurrency(string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        System.Threading.Tasks.Task<double> SellCurrencyAsync(string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHistoricalRates", ReplyAction="http://tempuri.org/IService1/GetHistoricalRatesResponse")]
        string GetHistoricalRates(string currencyCode, int days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHistoricalRates", ReplyAction="http://tempuri.org/IService1/GetHistoricalRatesResponse")]
        System.Threading.Tasks.Task<string> GetHistoricalRatesAsync(string currencyCode, int days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        int RegisterUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<int> RegisterUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        int LoginUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        System.Threading.Tasks.Task<int> LoginUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TopUp", ReplyAction="http://tempuri.org/IService1/TopUpResponse")]
        double TopUp(int userId, double amountPLN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TopUp", ReplyAction="http://tempuri.org/IService1/TopUpResponse")]
        System.Threading.Tasks.Task<double> TopUpAsync(int userId, double amountPLN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        double GetBalance(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        System.Threading.Tasks.Task<double> GetBalanceAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyForUser", ReplyAction="http://tempuri.org/IService1/BuyForUserResponse")]
        string BuyForUser(int userId, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyForUser", ReplyAction="http://tempuri.org/IService1/BuyForUserResponse")]
        System.Threading.Tasks.Task<string> BuyForUserAsync(int userId, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellForUser", ReplyAction="http://tempuri.org/IService1/SellForUserResponse")]
        string SellForUser(int userId, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellForUser", ReplyAction="http://tempuri.org/IService1/SellForUserResponse")]
        System.Threading.Tasks.Task<string> SellForUserAsync(int userId, string currencyCode, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserTransactions", ReplyAction="http://tempuri.org/IService1/GetUserTransactionsResponse")]
        string GetUserTransactions(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserTransactions", ReplyAction="http://tempuri.org/IService1/GetUserTransactionsResponse")]
        System.Threading.Tasks.Task<string> GetUserTransactionsAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ExchangeClient.ServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ExchangeClient.ServiceRef.IService1>, ExchangeClient.ServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public double Convert(string fromCurrency, string toCurrency, double amount) {
            return base.Channel.Convert(fromCurrency, toCurrency, amount);
        }
        
        public System.Threading.Tasks.Task<double> ConvertAsync(string fromCurrency, string toCurrency, double amount) {
            return base.Channel.ConvertAsync(fromCurrency, toCurrency, amount);
        }
        
        public double BuyCurrency(string currencyCode, double amount) {
            return base.Channel.BuyCurrency(currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<double> BuyCurrencyAsync(string currencyCode, double amount) {
            return base.Channel.BuyCurrencyAsync(currencyCode, amount);
        }
        
        public double SellCurrency(string currencyCode, double amount) {
            return base.Channel.SellCurrency(currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<double> SellCurrencyAsync(string currencyCode, double amount) {
            return base.Channel.SellCurrencyAsync(currencyCode, amount);
        }
        
        public string GetHistoricalRates(string currencyCode, int days) {
            return base.Channel.GetHistoricalRates(currencyCode, days);
        }
        
        public System.Threading.Tasks.Task<string> GetHistoricalRatesAsync(string currencyCode, int days) {
            return base.Channel.GetHistoricalRatesAsync(currencyCode, days);
        }
        
        public int RegisterUser(string username) {
            return base.Channel.RegisterUser(username);
        }
        
        public System.Threading.Tasks.Task<int> RegisterUserAsync(string username) {
            return base.Channel.RegisterUserAsync(username);
        }
        
        public int LoginUser(string username) {
            return base.Channel.LoginUser(username);
        }
        
        public System.Threading.Tasks.Task<int> LoginUserAsync(string username) {
            return base.Channel.LoginUserAsync(username);
        }
        
        public double TopUp(int userId, double amountPLN) {
            return base.Channel.TopUp(userId, amountPLN);
        }
        
        public System.Threading.Tasks.Task<double> TopUpAsync(int userId, double amountPLN) {
            return base.Channel.TopUpAsync(userId, amountPLN);
        }
        
        public double GetBalance(int userId) {
            return base.Channel.GetBalance(userId);
        }
        
        public System.Threading.Tasks.Task<double> GetBalanceAsync(int userId) {
            return base.Channel.GetBalanceAsync(userId);
        }
        
        public string BuyForUser(int userId, string currencyCode, double amount) {
            return base.Channel.BuyForUser(userId, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<string> BuyForUserAsync(int userId, string currencyCode, double amount) {
            return base.Channel.BuyForUserAsync(userId, currencyCode, amount);
        }
        
        public string SellForUser(int userId, string currencyCode, double amount) {
            return base.Channel.SellForUser(userId, currencyCode, amount);
        }
        
        public System.Threading.Tasks.Task<string> SellForUserAsync(int userId, string currencyCode, double amount) {
            return base.Channel.SellForUserAsync(userId, currencyCode, amount);
        }
        
        public string GetUserTransactions(int userId) {
            return base.Channel.GetUserTransactions(userId);
        }
        
        public System.Threading.Tasks.Task<string> GetUserTransactionsAsync(int userId) {
            return base.Channel.GetUserTransactionsAsync(userId);
        }
    }
}
